/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Autocomplete: typeof import('./src/components/nodes/autocomplete.vue')['default']
    Card: typeof import('./src/components/nodes/card.vue')['default']
    Checkbox: typeof import('./src/components/nodes/checkbox.vue')['default']
    CheckboxGroup: typeof import('./src/components/nodes/checkbox-group.vue')['default']
    ChildSubtitle: typeof import('./src/components/fragments/child-subtitle.vue')['default']
    ColorPicker: typeof import('./src/components/nodes/color-picker.vue')['default']
    Combobox: typeof import('./src/components/nodes/combobox.vue')['default']
    DatePicker: typeof import('./src/components/nodes/date-picker.vue')['default']
    DateTimePicker: typeof import('./src/components/nodes/date-time-picker.vue')['default']
    ExpansionPanels: typeof import('./src/components/nodes/expansion-panels.vue')['default']
    FileInput: typeof import('./src/components/nodes/file-input.vue')['default']
    HelpMessage: typeof import('./src/components/fragments/help-message.vue')['default']
    List: typeof import('./src/components/nodes/list.vue')['default']
    Node: typeof import('./src/components/node.vue')['default']
    NodeSlot: typeof import('./src/components/fragments/node-slot.vue')['default']
    NumberCombobox: typeof import('./src/components/nodes/number-combobox.vue')['default']
    NumberField: typeof import('./src/components/nodes/number-field.vue')['default']
    OneOfSelect: typeof import('./src/components/nodes/one-of-select.vue')['default']
    RadioGroup: typeof import('./src/components/nodes/radio-group.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Section: typeof import('./src/components/nodes/section.vue')['default']
    SectionHeader: typeof import('./src/components/fragments/section-header.vue')['default']
    Select: typeof import('./src/components/nodes/select.vue')['default']
    SelectionGroup: typeof import('./src/components/fragments/selection-group.vue')['default']
    SelectItem: typeof import('./src/components/fragments/select-item.vue')['default']
    SelectItemIcon: typeof import('./src/components/fragments/select-item-icon.vue')['default']
    SelectSelection: typeof import('./src/components/fragments/select-selection.vue')['default']
    Slider: typeof import('./src/components/nodes/slider.vue')['default']
    Stepper: typeof import('./src/components/nodes/stepper.vue')['default']
    Switch: typeof import('./src/components/nodes/switch.vue')['default']
    SwitchGroup: typeof import('./src/components/nodes/switch-group.vue')['default']
    Tabs: typeof import('./src/components/nodes/tabs.vue')['default']
    Textarea: typeof import('./src/components/nodes/textarea.vue')['default']
    TextField: typeof import('./src/components/nodes/text-field.vue')['default']
    TextFieldMenu: typeof import('./src/components/fragments/text-field-menu.vue')['default']
    TimePicker: typeof import('./src/components/nodes/time-picker.vue')['default']
    Tree: typeof import('./src/components/tree.vue')['default']
    VerticalTabs: typeof import('./src/components/nodes/vertical-tabs.vue')['default']
    Vjsf: typeof import('./src/components/vjsf.vue')['default']
  }
}
