// same as VJsjNoDeps but requiring each used component of vuetify to try working well with vuetify-loader

import VJsfNoNeps from './VJsfNoDeps'

import {
  VAvatar,
  VAutocomplete,
  VBtn,
  VCard,
  VCardActions,
  VCardText,
  VCardTitle,
  VCheckbox,
  VChip,
  VCombobox,
  VContainer,
  VDatePicker,
  VDialog,
  VExpansionPanels,
  VExpansionPanel,
  VExpansionPanelHeader,
  VExpansionPanelContent,
  VFlex,
  VIcon,
  VInput,
  VLayout,
  VListItemContent,
  VListItemTitle,
  VListTileContent,
  VListTileTitle,
  VMenu,
  VSelect,
  VSpacer,
  VSubheader,
  VTabs,
  VTab,
  VTabItem,
  VTextarea,
  VTextField,
  VTimePicker,
  VTooltip
} from 'vuetify/lib'

export default {
  name: 'VJsf',
  components: {
    VAvatar,
    VAutocomplete,
    VBtn,
    VCard,
    VCardActions,
    VCardText,
    VCardTitle,
    VCheckbox,
    VChip,
    VCombobox,
    VContainer,
    VDatePicker,
    VDialog,
    VExpansionPanels,
    VExpansionPanel,
    VExpansionPanelHeader,
    VExpansionPanelContent,
    VFlex,
    VIcon,
    VInput,
    VLayout,
    VListItemContent,
    VListItemTitle,
    VListTileContent,
    VListTileTitle,
    VMenu,
    VSelect,
    VSpacer,
    VSubheader,
    VTabs,
    VTab,
    VTabItem,
    VTextarea,
    VTextField,
    VTimePicker,
    VTooltip
  },
  mixins: [VJsfNoNeps]
}
