// same as VJsjNoDeps but requiring each used component of vuetify to try working well with vuetify-loader

import VJsfNoNeps from './VJsfNoDeps'

import {
  ClickOutside,
  VAlert,
  VAvatar,
  VAutocomplete,
  VBtn,
  VCard,
  VCardActions,
  VCardText,
  VCardTitle,
  VCheckbox,
  VChip,
  VColorPicker,
  VCombobox,
  VContainer,
  VDatePicker,
  VDialog,
  VExpansionPanels,
  VExpansionPanel,
  VExpansionPanelHeader,
  VExpansionPanelContent,
  VCol,
  VFileInput,
  VIcon,
  VInput,
  VRow,
  VList,
  VListItem,
  VListItemContent,
  VListItemIcon,
  VListItemTitle,
  VListItemAction,
  VMenu,
  VRadio,
  VRadioGroup,
  VSelect,
  VSlider,
  VSpacer,
  VStepper,
  VStepperContent,
  VStepperHeader,
  VStepperItems,
  VStepperStep,
  VSubheader,
  VSwitch,
  VTabs,
  VTab,
  VTabItem,
  VTextarea,
  VTextField,
  VTimePicker,
  VTooltip
} from 'vuetify/lib'

export default {
  name: 'VJsf',
  directives: { ClickOutside },
  components: {
    VAlert,
    VAvatar,
    VAutocomplete,
    VBtn,
    VCard,
    VCardActions,
    VCardText,
    VCardTitle,
    VCheckbox,
    VChip,
    VColorPicker,
    VCombobox,
    VContainer,
    VDatePicker,
    VDialog,
    VExpansionPanels,
    VExpansionPanel,
    VExpansionPanelHeader,
    VExpansionPanelContent,
    VCol,
    VFileInput,
    VIcon,
    VInput,
    VRow,
    VList,
    VListItem,
    VListItemContent,
    VListItemIcon,
    VListItemTitle,
    VListItemAction,
    VMenu,
    VRadio,
    VRadioGroup,
    VSelect,
    VSlider,
    VSpacer,
    VStepper,
    VStepperContent,
    VStepperHeader,
    VStepperItems,
    VStepperStep,
    VSubheader,
    VSwitch,
    VTabs,
    VTab,
    VTabItem,
    VTextarea,
    VTextField,
    VTimePicker,
    VTooltip
  },
  mixins: [VJsfNoNeps]
}
